# My current kitty settings.
# Made by Ruben_&_Linux:~ to Artix Linux.

# To get a full list of supported fonts use the `kitty +list-fonts` command.
#font_family     IosevkaTerm Nerd Font
font_family      JetBrainsMono Nerd Font
font_size 11.5

scrollback_lines 8000

paste_actions quote-urls-at-prompt

strip_trailing_spaces never

select_by_word_characters @-./_~?&=%+#

show_hyperlink_targets yes

remote_kitty if-needed

share_connections yes

mouse_map left click ungrabbed no-op

mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt

mouse_map ctrl+left press ungrabbed mouse_selection normal

mouse_map right press ungrabbed copy_to_clipboard

window_padding_width 5

remember_window_size  no
initial_window_width  800
initial_window_height 490

enabled_layouts splits,stack
#enabled_layouts all

include splits.conf

window_resize_step_cells 2
window_resize_step_lines 2

window_border_width 0.5pt

visual_window_select_characters 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

confirm_os_window_close -1

tab_bar_style powerline

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}:{'🇿' if layout_name == 'stack' and num_windows > 1 else ''}{title}"

background_opacity 0.80

background_image none

background_image_layout tiled

background_image_linear no

dynamic_background_opacity yes

allow_remote_control yes

startup_session session.conf

allow_hyperlinks yes

shell_integration enabled

#term xterm-kitty
term xterm-256color

kitty_mod ctrl+shift

#map kitty_mod+enter new_window
map kitty_mod+enter no-op
map cmd+enter       no-op

map ctrl+a>x close_window

map ctrl+a>] next_window

map ctrl+a>[ previous_window

map ctrl+a>period move_window_forward

map ctrl+a>comma move_window_backward

#map kitty_mod+t new_tab_with_cwd
# map kitty_mod+t new_tab
map kitty_mod+t launch --location=hsplit

map ctrl+a>c launch --cwd=last_reported --type=tab

map ctrl+a>, set_tab_title

map ctrl+equal  change_font_size all +2.0
map ctrl+plus   change_font_size all +2.0
map ctrl+kp_add change_font_size all +2.0

map ctrl+minus       change_font_size all -2.0
map ctrl+kp_subtract change_font_size all -2.0

#: Reset font size

map ctrl+0 change_font_size all 0

map f11 toggle_fullscreen

# map ctrl+a>e edit_config_file
map ctrl+a>e no-op
map ctrl+a>shift+e launch --type=tab nvim ~/.config/kitty/kitty.conf

#: Reload kitty.conf

map ctrl+a>shift+r combine : load_config_file : launch --type=overlay sh -c 'echo "kitty config reloaded."; echo; read -r -p "Press Enter to exit"; echo ""'

#: Debug kitty configuration

map ctrl+a>shift+d     debug_config

# BEGIN_KITTY_THEME
include nord-kitty.conf

map ctrl+a>space kitten hints --alphabet asdfqwerzxcvjklmiuopghtybn1234567890 --customize-processing custom-hints.py

map f3 kitten hints --program '*'

map ctrl+a>ctrl+a send_text all \x01
